# Generated by Django 4.0.3 on 2022-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_alter_hobbies_name_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='act',
            field=models.ManyToManyField(to='hobbies.hobbies'),
        ),
    ]
